# Update translations when the english master changes

update-po:
	msgmerge -U --no-wrap resource.language.cs_cz/strings.po resource.language.en_gb/strings.po
	msgmerge -U --no-wrap resource.language.de_de/strings.po resource.language.en_gb/strings.po
	msgmerge -U --no-wrap resource.language.el_gr/strings.po resource.language.en_gb/strings.po
	msgmerge -U --no-wrap resource.language.es_es/strings.po resource.language.en_gb/strings.po
	msgmerge -U --no-wrap resource.language.gl_es/strings.po resource.language.en_gb/strings.po
	msgmerge -U --no-wrap resource.language.hr_hr/strings.po resource.language.en_gb/strings.po
	msgmerge -U --no-wrap resource.language.hu_hu/strings.po resource.language.en_gb/strings.po
	msgmerge -U --no-wrap resource.language.it_it/strings.po resource.language.en_gb/strings.po
	msgmerge -U --no-wrap resource.language.iw_il/strings.po resource.language.en_gb/strings.po
	msgmerge -U --no-wrap resource.language.nl_nl/strings.po resource.language.en_gb/strings.po
	msgmerge -U --no-wrap resource.language.no_no/strings.po resource.language.en_gb/strings.po
	msgmerge -U --no-wrap resource.language.ro_ro/strings.po resource.language.en_gb/strings.po
	msgmerge -U --no-wrap resource.language.sk_sk/strings.po resource.language.en_gb/strings.po
	msgmerge -U --no-wrap resource.language.sv_se/strings.po resource.language.en_gb/strings.po
